version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    platform: linux/x86_64
    volumes:
      - "./sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=auth
